version: "3"

services:
  hive-metastore-db:
    image: ${MYSQL_IMAGE}
    hostname: metastore-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=hive_metastore
    tty: true

  hadoop:
    build:
      context: .
      dockerfile: hadoop/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        AUTHENTICATION_TYPE: noauth
    environment:
      - HADOOP_CONF_SUBSTITUTE_DATANODE_HOSTNAME=${DOCKER_HOST_HOSTNAME}
    hostname: hadoop-server
    extra_hosts:
      - "${DOCKER_HOST_HOSTNAME}:host-gateway"
    ports:
      - "9000:9000"
      - "9870:9870"
      - "9864:9864"
      - "9866:9866"
    tty: true

  hive:
    build:
      context: .
      dockerfile: hive/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        HIVE_VERSION: ${HIVE_VERSION}
        AUTHENTICATION_TYPE: noauth
    environment:
      HIVE_CONF_SUBSTITUTE_HDFS_HOST: ${DOCKER_HOST_HOSTNAME}:9000
      HIVE_CONF_SUBSTITUTE_METASTORE_DB_USER: ${SQL_USER}
      HIVE_CONF_SUBSTITUTE_METASTORE_DB_PASSWORD: ${SQL_PASSWORD}
      SERVICE_DEPENDENCIES: "metastore-db:3306 hadoop-server:55555"
    hostname: hive-server
    ports:
      - "9083:9083"
      - "10000:10000"
      - "10002:10002"
    depends_on:
      - hive-metastore-db
      - hadoop
    links:
      - hadoop:${DOCKER_HOST_HOSTNAME}
    tty: true

  kerberos:
    build:
      context: .
      dockerfile: kerberos/Dockerfile
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    hostname: kerberos-server
    tty: true

  kerberized-hadoop:
    build:
      context: .
      dockerfile: hadoop/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        AUTHENTICATION_TYPE: kerberos
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    environment:
      SERVICE_DEPENDENCIES: "kerberos-server:749"
    hostname: hadoop-server
    depends_on:
      - kerberos
    tty: true

  kerberized-hive:
    build:
      context: .
      dockerfile: hive/Dockerfile
      args:
        JDK_IMAGE: ${JDK_IMAGE}
        HADOOP_VERSION: ${HADOOP_VERSION}
        HIVE_VERSION: ${HIVE_VERSION}
        AUTHENTICATION_TYPE: kerberos
    volumes:
      - ./kerberos/keytabs:/var/keytabs
    environment:
      SERVICE_DEPENDENCIES: "metastore-db:3306 kerberos-server:749 hadoop-server:55555"
    hostname: hive-server
    depends_on:
      - hive-metastore-db
      - kerberos
      - kerberized-hadoop
    tty: true
